### PR TITLE
Changes to fix Issue #20

### PR DESCRIPTION
**Pull request by qgarcia95**
The 'Contact Us' button is now styled using CSS rather than Tailwind CSS. I made a class for the button in the styles/Home.module.css called 'contactUs' to style the button accordingly. I hope this works, I made minor style changes to the button design that was initially there.

### CODE REVIEW

**Comment by amoweolubusayo** [comment]
Hello @qgarcia95. Thank you for contributing… We actually intend to make our stack uniform. So, there’s an agreement to use tailwind css as opposed to normal css.

**Comment by qgarcia95** [comment]
I will change it accordingly then sorry, ill resubmit it for review once I am done

**Comment by qgarcia95** [comment]
@amoweolubusayo okay i reverted it back to tailwind and made changes to fix padding of button. Is this what was needed? Please let me know what is still needed. Thanks

**Comment by qgarcia95** [comment]
@amoweolubusayo did you get a chance to re-review it?

**Comment by amoweolubusayo** [comment]
Not yet! Thanks for the reminder. @qgarcia95

**Review by oceans404 — APPROVED** [review]
Looks great! And thanks for fixing the indentation while you were working on this.

**Comment by qgarcia95** [comment]
Your  welcome, thanks for letting me work on this issue.

**Pull request merged**
