### PR TITLE
Merging

### PR DESCRIPTION
**Pull request by meowyx**

### CODE REVIEW

**Comment by sarahschwartz** [comment]
looks like there are some spacing issues here (contact button on desktop, centered text on mobile).  I also think we might want to make the text colors more consistent on the page? I think we should vote on our latest designs in discord

**Comment by amoweolubusayo** [comment]
I agree with Sarah @myaowy. There are some responsiveness issues around the contact button. Please can you fix them @myaowy? We can also create them as issues if it will be necessary. I think we need some form of collab/meeting to conclude/agree on the text colors as well.

**Comment by meowyx** [comment]
@amoweolubusayo @sarahschwartz  okay lets hold meetings soon, I think I also need to check, because the merging failed so many times that I messed up.

**Comment by amoweolubusayo** [comment]
No worries at all. I guess it's a learning process for all of us :)

**Comment by meowyx** [comment]
@amoweolubusayo yesterday when I did that there wasnt any responsive problems so I have to check a bit

**Comment by meowyx** [comment]
@amoweolubusayo @sarahschwartz thank you for giving me heads up, I will fix it by today

**Pull request closed without merging**
