### PR TITLE
fix: about page

### PR DESCRIPTION
**Pull request by amoweolubusayo**
@sarahschwartz i'm thinking. should there be a call to action to our whitepaper from this page?

### CODE REVIEW

**Comment by sarahschwartz** [comment]
@amoweolubusayo yeah for sure. For some reason it looks like the preview build failed for this though

**Comment by amoweolubusayo** [comment]
@sarahschwartz fixed. Please help to review 😅. My bad too many commits but just 1 file change. I have been having issues running it locally.

**Comment by sarahschwartz** [comment]
Nice! I think we could split the about page into sections too, like our mission, values, and goals

**Review by sarahschwartz — APPROVED** [review]

**Comment by amoweolubusayo** [comment]
Good Idea @sarahschwartz . Thought about it actually but was thinking if they saw all on the website they might not be curious to go check out white paper. However, brief summary of this secrions isn’t bad at all actually. I would work on that. Thanks!!

**Pull request merged**
